-- ====================================================================
-- 원형 하루 시간표 & Pushwing Web Push 통합 데이터베이스 스키마
-- Supabase SQL Editor (https://supabase.com/dashboard/project/jtwjwbqgwreyyhjfoptj/sql)
-- ====================================================================

-- 1. 시간표 테이블 (schedules)
create table if not exists public.schedules (
  id text primary key,
  user_id uuid references auth.users(id) on delete set null,
  title text not null default '나의 하루 시간표',
  items jsonb not null default '[]'::jsonb,
  is_public boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.schedules enable row level security;

create policy "Public schedules are viewable by everyone" 
on public.schedules for select 
using (is_public = true or auth.uid() = user_id);

create policy "Anyone can insert schedules" 
on public.schedules for insert 
with check (true);

create policy "Users can update own schedules" 
on public.schedules for update 
using (auth.uid() = user_id);

create policy "Users can delete own schedules" 
on public.schedules for delete 
using (auth.uid() = user_id);


-- 2. 관리자 롤 (user_roles) 테이블
create table if not exists public.user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  email text not null,
  role text not null default 'user', -- 'admin' 또는 'user'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint unique_user_role unique (user_id, role)
);

alter table public.user_roles enable row level security;

create policy "Allow all read on user_roles" 
on public.user_roles for select 
using (true);

create policy "Allow all insert on user_roles" 
on public.user_roles for insert 
with check (true);

create policy "Allow all update on user_roles" 
on public.user_roles for update 
using (true);

create policy "Allow all delete on user_roles" 
on public.user_roles for delete 
using (true);


-- 3. Pushwing 앱/테넌트 테이블 (apps)
create table if not exists public.apps (
  app_key text primary key,
  app_name text not null,
  secret_key text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.apps enable row level security;

create policy "Allow all read apps" 
on public.apps for select 
using (true);

create policy "Allow all insert apps" 
on public.apps for insert 
with check (true);

create policy "Allow all delete apps" 
on public.apps for delete 
using (true);


-- 4. Pushwing 웹 푸시 구독 테이블 (subscriptions)
create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  app_key text not null references public.apps(app_key) on delete cascade,
  user_id text not null,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.subscriptions enable row level security;

create policy "Allow all operations on subscriptions" 
on public.subscriptions for all 
using (true);


-- 5. Pushwing 푸시 발송 이력 테이블 (push_logs)
create table if not exists public.push_logs (
  id bigint generated by default as identity primary key,
  app_key text not null,
  title text not null,
  body text not null,
  url text,
  success_count integer default 0,
  fail_count integer default 0,
  sent_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.push_logs enable row level security;

create policy "Allow all operations on push_logs" 
on public.push_logs for all 
using (true);


-- 6. 기본 데모 앱 키 등록 (없을 경우)
insert into public.apps (app_key, app_name, secret_key)
values ('demo-app-key-2026', 'Pushwing Demo App', 'demo-secret-key-2026')
on conflict (app_key) do nothing;

-- 7. kimdongup@gmail.com 관리자 롤 자동 부여
insert into public.user_roles (email, role)
values ('kimdongup@gmail.com', 'admin')
on conflict (email) do update set role = 'admin';