-- ====================================================================

create extension if not exists pgcrypto;
-- 원형 하루 시간표 & 표준 Web Push 통합 데이터베이스 스키마
-- Supabase SQL Editor (https://supabase.com/dashboard/project/jtwjwbqgwreyyhjfoptj/sql)
-- ====================================================================

-- 1. 시간표 테이블 (schedules)
create table if not exists public.schedules (
  id text primary key,
  user_id uuid references auth.users(id) on delete set null,
  title text not null default '나의 하루 시간표',
  items jsonb not null default '[]'::jsonb,
  is_public boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.schedules enable row level security;

drop policy if exists "Public schedules are viewable by everyone" on public.schedules;
drop policy if exists "Anyone can insert schedules" on public.schedules;
drop policy if exists "Guests and users can insert schedules" on public.schedules;
drop policy if exists "Users can update schedules" on public.schedules;
drop policy if exists "Users can delete schedules" on public.schedules;

create policy "Public schedules are viewable by everyone" 
on public.schedules for select 
using (is_public = true or auth.uid() = user_id);

create policy "Guests and users can insert schedules"
on public.schedules for insert 
with check (
  (is_public = true and user_id is null)
  or auth.uid() = user_id
);

create policy "Users can update schedules" 
on public.schedules for update 
using (auth.uid() = user_id or (is_public = true and user_id is null))
with check (auth.uid() = user_id or (is_public = true and user_id is null));

create policy "Users can delete schedules" 
on public.schedules for delete 
using (is_public = false and auth.uid() = user_id);


-- 2. 관리자 롤 (user_roles) 테이블
create table if not exists public.user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  email text not null unique,
  role text not null default 'user', -- 'admin' 또는 'user'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.user_roles enable row level security;

-- user_roles는 Vercel 서버의 service-role 클라이언트만 접근합니다.
drop policy if exists "Allow all operations on user_roles" on public.user_roles;


-- 3. Web Push 앱/테넌트 테이블 (apps)
create table if not exists public.apps (
  app_key text primary key,
  app_name text not null,
  secret_key text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.apps enable row level security;

-- secret_key 보호를 위해 브라우저 직접 접근을 허용하지 않습니다.
drop policy if exists "Allow all operations on apps" on public.apps;


-- 4. Web Push 구독 테이블 (subscriptions)
create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  app_key text not null references public.apps(app_key) on delete cascade,
  user_id text not null,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.subscriptions enable row level security;

-- Push 구독 정보는 Vercel API에서만 관리합니다.
drop policy if exists "Allow all operations on subscriptions" on public.subscriptions;


-- 5. Web Push 발송 이력 테이블 (push_logs)
create table if not exists public.push_logs (
  id bigint generated by default as identity primary key,
  app_key text not null,
  title text not null,
  body text not null,
  url text,
  success_count integer default 0,
  fail_count integer default 0,
  sent_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.push_logs enable row level security;

-- Push 발송 이력은 Vercel API에서만 관리합니다.
drop policy if exists "Allow all operations on push_logs" on public.push_logs;


-- 6. 기본 데모 앱 키 등록 (없을 경우)
insert into public.apps (app_key, app_name, secret_key)
values ('demo-app-key-2026', 'Circular Schedule', encode(gen_random_bytes(24), 'hex'))
on conflict (app_key) do nothing;

update public.apps
set app_name = 'Circular Schedule'
where app_key = 'demo-app-key-2026';

-- 과거 예제 Secret Key가 남아 있다면 한 번만 안전한 난수로 교체합니다.
update public.apps
set secret_key = encode(gen_random_bytes(24), 'hex')
where app_key = 'demo-app-key-2026'
  and secret_key = 'demo-secret-key-2026';

-- 관리자는 Vercel의 ADMIN_EMAILS 환경 변수로 지정하거나 아래 예시를 직접 실행합니다.
-- insert into public.user_roles (email, role)
-- values ('admin@example.com', 'admin')
-- on conflict (email) do update set role = 'admin';
